language: python
python:
  - "3.5"
install: 
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash ./Miniconda3-latest-Linux-x86_64.sh 
    - conda env create -f environment.yml
    - source activate convolutional_network_environment
script: py.test